{
 "title": "Logs_Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Process Virtual Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "alloy_resources_process_virtual_memory_bytes{job=\"alloy\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Resident Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "alloy_resources_process_resident_memory_bytes{job=\"alloy\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "alloy_resources_process_cpu_seconds_total{job=\"alloy\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Local Logs Count",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=\"/tmp/sample-logs/test.log\"}"
    }
   ]
  }
 ]
}